### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/u-bahn-app#6]
## TODOS

- [x] Search by location: User should type a location and the related location should show up. In case there are no locations found, display a message indicating the same
- [x] Search by location: Update api request to pass the location selected as an attribute filter. Currently it is passing it as `locations` filter
- [x] Support sorting by user name, location and availability.
- [x] Support availability filters
- [x] Support skill filters
- [x] Support achievement filters
- [x] Add a filter: Support company attributes filter
- [x] Support filter by groups
- [x] Get and display the groups for the sidebar filter
- [x] Connect with Search UI API to download the template for bulk uploads
- [x] Connect with Search UI API to upload the bulk upload file
- [x] Integrate Auth0 based authorization
- [x] Add group modal. Get all the groups to list in the modal, and when toggled, add / remove the user from the group
- [x] Get the groups for a user and display it against that user
- [x] Edit user modal: Editing name, role, company, location should call the api with the updates
- [x] Edit user modal: Entering a new skill should show suggestions from EMSI
- [x] Edit user modal: Achievements
- [x] Edit user modal: Editing attribute values should pass the updates to the api
- [x] Delete user

## Testing

Once TODOs are completed, verify changes made:

- [x] Test pagination of the user listing. It seems to work in demo, but my test data has only 2 records for now so cannot verify
- [x] Clicking on reset should reset all filters

**Comment by callmekatootie** [comment]
## Assumptions

- Attributes `isAvailable`, `location`, `company` and `title` would exist for all users. Without this, UI will not know the attribute id when any of these attributes would get a value through the UI.
